<a href="https://colab.research.google.com/github/anhelus/pcs-exercises/blob/master/01_libs/01_numpy/01_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Esercitazione 1 - NumPy e l'algebra**

In questa esercitazione andremo ad introdurre i principali concetti legati all'utilizzo di NumPy in ambito algebrico.

In [1]:
import numpy as np

**Matrice trasposta**

Per calcolare la **trasposta** di una matrice, usiamo la funzione [`numpy.transpose()`](https://numpy.org/doc/stable/reference/generated/numpy.transpose.html).

In [2]:
x = np.array([[1, 2, 3], [4, 5, 6]])
np.transpose(x)

array([[1, 4],
       [2, 5],
       [3, 6]])

**Matrice inversa**

Per calcolare l'**inversa** di una matrice, usiamo la funzione `inv` del package `linalg`.

In [3]:
x = np.array([[5, 0, 0], [0, 2, 0], [0, 0, 4]])
np.linalg.inv(x)

array([[0.2 , 0.  , 0.  ],
       [0.  , 0.5 , 0.  ],
       [0.  , 0.  , 0.25]])

Se proviamo a calcolare l'inversa di una matrice rettangolare o di una matrice singolare, la funzione `inv` restituirà un errore di tipo `LinAlgError`.

In [4]:
try:
    mat = np.array([[1, 2, 3], [4, 5, 6]])
    np.linalg.inv(mat)
except np.linalg.LinAlgError:
    print('Questo è ciò che accade se usiamo una matrice rettangolare!')
try:
    mat = np.array([[1,1,1],[2,2,2],[0,0,1]])
    np.linalg.inv(mat)
except np.linalg.LinAlgError:
    print('Questo è ciò che accade se usiamo una matrice singolare!')

Questo è ciò che accade se usiamo una matrice rettangolare!
Questo è ciò che accade se usiamo una matrice singolare!


**Prodotti matriciali**

Usiamo la funzione `inner` per calcolare il prodotto **scalare** tra due vettori. Partiamo con un caso monodimensionale:

In [5]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Il prodotto interno è (1*4)+(2*5)+(3*6)
np.inner(a, b)

np.int64(32)

Vediamo cosa accade in un caso multidimensionale:

In [6]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[0, 1], [1, 0]])

np.inner(a, b)

array([[2, 1],
       [4, 3]])

In questo caso, la formulazione è del tipo:

$$
p = \left[
    \begin{array}{cc}
        a_1 * b_1 + a_2 * b_2 & a_1 * b_3 + a_2 * b_4 \\
        a_3 * b_1 + a_4 * b_2 & a_3 * b_3 + a_4 * b_4
    \end{array}
\right] = \\
=\left[
    \begin{array}{cc}
        1 * 0 + 2 * 1 && 1 * 1 + 2 * 0 \\
        3 * 0 + 4 * 1 && 3 * 1 + 4 * 0
    \end{array}
\right]
= \left[
    \begin{array}{cc}
        2 & 1 \\
        4 & 3
    \end{array}
\right]
$$

**Prodotto esterno**

Il prodotto **esterno** viene calcolato mediante la funzione `outer`:

In [7]:
a = np.array([1, 2])
b = np.array([3, 4])

np.outer(a, b)

array([[3, 4],
       [6, 8]])

**La funzione matmul()**

La funzione `matmul` ci permette di effettuare il **prodotto matriciale** tra due matrici.

In [8]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

np.matmul(a, b)

array([[19, 22],
       [43, 50]])

`matmul()` non può essere usata con uno scalare come parametro, a differenza della `dot()`:

In [9]:
try:
  np.matmul(a, 3)
except ValueError:
  print('matmul non può essere usata con uno scalare!')

matmul non può essere usata con uno scalare!


**Potenza di matrice**

Per **elevare la matrice a potenza** utilizzare la funzione `matrix_power` del package `linalg`:

In [10]:
np.linalg.matrix_power(a, 5)

array([[1069, 1558],
       [2337, 3406]])

**Autovettori ed autovalore**

Per calcolare **autovettori ed autovalori** di una matrice, usiamo la funzione `eig` del package `linalg`:

In [11]:
(w, v) = np.linalg.eig(a)
print('Autovalori:', w, '\nAutovettori:', v)

Autovalori: [-0.37228132  5.37228132] 
Autovettori: [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


**Norma, rango, determinante e traccia**

Per calcolare la norma, usiamo la funzione `norm`:

In [12]:
np.linalg.norm(a)

np.float64(5.477225575051661)

Per calcolare rango, determinante e traccia, usiamo rispettivamente:

In [13]:
# Rango:
rank = np.linalg.matrix_rank(a)
det = np.linalg.det(a)
tr = np.trace(a)

print('Rango:', rank, '\nDeterminante:', det, '\nTraccia:', tr)

Rango: 2 
Determinante: -2.0000000000000004 
Traccia: 5


Per risolvere il seguente sistema di equazioni lineari:

$$
\begin{cases}
x_1 + 2 x_2 + 5 x_3 = y \\
2 x_1 + 2 x_2 + 3 x_3 = 3 y \\
2 x_1 + 2 x_2 + x_3 = 2 y
\end{cases}
$$

In [14]:
x = np.array([[1, 2, 2], [2, 2, 2], [5, 3, 1]])
y = np.array([1, 3, 2])

np.linalg.solve(x, y)

array([ 2.  , -3.75,  3.25])